### ISSUE TITLE
Bjoern Logging

### ISSUE THREAD

**Issue by vasudevavarun** [jonashaag/bjoern#100]
Hi,
I've implemented bjoern on one of ours python API server. I've couple of questions which I'm not able to sort.
Firstly, I want to enable logging in bjoern server with http codes.
Secondly, I want to put userid and password on every hit like we do in apache htaccess or any other recommended way to secure bjoern server.

Thanks in advance.

**Comment by jonashaag** [comment]
Hi, thanks for trying out bjoern. Please use the Gitter chat for support requests.

You can implement logging using WSGI middleware.

You can implement HTTP authentication using WSGI middleware, or in your reverse proxy server.
