### ISSUE TITLE
Asyncio support

### ISSUE THREAD

**Issue by thedrow** [jonashaag/bjoern#105]
Any chance that after #104 is merged someone will integrate asyncio support into bjoern?

**Comment by yanghao** [comment]
What do you mean exactly by "asyncio support in bjoern"? Bjoern is already an event-loop based implementation in C.

**Comment by thedrow** [comment]
I mean that the server will support [ASGI](http://channels.readthedocs.io/en/stable/asgi.html) like [uvicorn](https://github.com/encode/uvicorn) does.

**Comment by jonashaag** [comment]
Nope, this would mean a complete rewrite. Besides, there's already uvicorn and other alternatives, so what's the need for a new asyncio server?

**Comment by thedrow** [comment]
Just asking :) bjoern is simply so much faster...

**Comment by jonashaag** [comment]
> Just asking :) bjoern is simply so much faster...

Really? What benchmarks have you been using? Like, I know bjoern is faster for Hello World benchmarks, but in my experiments, as soon as you start running some real Python code it doesn't really matter. Have you done some real world benchmarks with these servers?

**Comment by thedrow** [comment]
I have seen the benchmarks posted in #75
