### ISSUE TITLE
Segmentation fault after the first request

### ISSUE THREAD

**Issue by prasadasokan** [jonashaag/bjoern#114]
We are seeing Process /usr/local/bin/python2.7 was killed by signal 11 (SIGSEGV). The first request returns a successful response, and then when we make the second request, it fails. What's causing this?

**Comment by jonashaag** [comment]
Maybe same issue as #113. Could you provide a minimal reproducing example? I'm having difficulties reproducing.

**Comment by jonashaag** [comment]
Found it! Fix is released as 2.0.4.

**Comment by prasadasokan** [comment]
Jonas,

Thanks for the quick fix. Will update to 2.0.4 and shall get back.

Regards,
Prasad Asokan.

On 23-Nov-2017, at 1:18 AM, Jonas Haag <notifications@github.com> wrote:

Closed #114 <https://github.com/jonashaag/bjoern/issues/114>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jonashaag/bjoern/issues/114#event-1354759521>, or mute
the thread
