### ISSUE TITLE
Please provide how to deploy bjoern django with apache2

### ISSUE THREAD

**Issue by ashoksiri** [jonashaag/bjoern#117]
when i run 

<h4>import os

from django.core.wsgi import get_wsgi_application
import bjoern

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "samplesite.settings")

application = get_wsgi_application()

bjoern.run(application,'0.0.0.0',8888)
</h4>
it is giving me unable to load settings madule

so can please tell me the process

**Comment by jonashaag** [comment]
Sorry, this is not a support forum. Please ask here: https://gitter.im/jonashaag/bjoern
