### ISSUE TITLE
request['context'].META['QUERY_STRING'] key error

### ISSUE THREAD

**Issue by AlexProfi** [jonashaag/bjoern#118]
I use mezzanine cms and mezzanine_tags
if context['request'].META["QUERY_STRING"]: in that code error ocured
key error query_string
bjoern runs on unix socket
how transfer this headers
because in META is much less elements than in original django request on dev server

**Comment by jonashaag** [comment]
Does this really have anything to do with bjoern? Does it work with other servers?

**Comment by jonashaag** [comment]
If you're talking about this line: https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/core/templatetags/mezzanine_tags.py#L724

That's a bug in Mezzanine; it's a bug to assume `QUERY_STRING` is in the WSGI environment.

**Comment by AlexProfi** [comment]
with uwsgi it works fine
with gunicorn I don't try

**Comment by AlexProfi** [comment]
yes about this line/ I test what is in request['context'].META and there is no element with key QUERY_STRING

**Comment by AlexProfi** [comment]
but in uwsgi this key in META exists
