### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by ryanisnan** [jonashaag/bjoern#119]
Trying to install bjoern locally and on Heroku fails with the same message, e.g.

```
$ pip --version
pip 9.0.1 from /path/to/python2.7/site-packages (python 2.7)

$ pip install bjoern
...
bjoern/request.h:4:16: fatal error: ev.h: No such file or directory
...
Failed building wheel for bjoern
```
Any thoughts?

**Comment by ryanisnan** [comment]
Full traceback here: http://dpaste.com/1CMTYRF

**Comment by yanxurui** [comment]
Do you have libev_devel?

发自我的 iPhone

**Comment by ryanisnan** [comment]
Thanks for the quick comment - yes that seemed to be the issue. Would this requirement make sense to be listed in the installation instructions? I realize that after looking at the error I should have realized it was failing on ev.h and tracked that down, but I appreciate the assistance.

**Comment by jonashaag** [comment]
What OS is this? If it's not in the installation instructions feel free to add it.

**Comment by andyforceno** [comment]
I had the same issue with Ubuntu 14.04. `sudo apt-get install libev-dev` fixed it.

**Comment by olymk2** [comment]
Just hit this myself on debian, tried installing the files below

    apt install libev-dev libevdev2

There does not seem to be anything called libev_devel in debian or ubuntu.

**Comment by jonashaag** [comment]
https://packages.ubuntu.com/artful/libev-dev
https://packages.debian.org/de/sid/libev-dev

**Comment by jonashaag** [comment]
Did this work for you?

**Comment by olymk2** [comment]
I got it working, not sure how doing apt install libev-dev && pip install bjoern works using pip install requirements.txt does not and fails to find the header file.

likely something else happening so i will dig further.

**Comment by tedaky** [comment]
Is anyone know how to get it working in Windows. brew install libev and apt install libev-dev libevdev2 is not a valid comment in windows.

**Comment by jonashaag** [comment]
Bjoern does not support Windows
