### ISSUE TITLE
When the custom request header is sent, the variable will be lost during the transmission if the request header contains a custom variable containing the underline.

### ISSUE THREAD

**Issue by justonlyyo** [jonashaag/bjoern#124]
example:
flask_server.py
`
#  -*- coding: utf-8 -*-
from flask import Flask
from flask import request
import json

app = Flask(__name__)

"""flask server example"""

@app.route("/")
def example():
    token = request.headers.get("auth-token")
    result = {"token": token}
    return json.dumps(result)

if __name__ == "__main__":
    app.run("0.0.0.0", port=5000)
`

bjoern_server.py
`
#  -*- coding: utf-8 -*-
from flask_server import app
import bjoern

"""bjoern server example"""

bjoern.listen(app, "0.0.0.0", 6000)
bjoern.run()
`
client_example.py
`
#  -*- coding: utf-8 -*-
import requests
from uuid import uuid4

"""client example"""

def example(url: str) -> None:
    token = uuid4().hex
    data = {"auth-token": token}
    r = requests.get(url=url, data=data)
    print(r.json())

if __name__ == "__main__":
    example("http://127.0.0.1:5000")
    example("http://127.0.0.1:6000")
`
run  flask_server.py
run  bjoern_server.py
run client_example.py

result: 
`
pydev debugger: process 24609 is connecting

Connected to pydev debugger (build 172.4343.24)
{'token': '85d73ecc361344e48bc2356cecc9b006'}
{'token': 'dfbc29a52d63494eb8760c70fa212a23'}

Process finished with exit code 0

`
change token's name, from 'auth-token' to 'auth_token'

flask_server.py
`
#  -*- coding: utf-8 -*-
from flask import Flask
from flask import request
import json

app = Flask(__name__)

"""flask server example"""

@app.route("/")
def example():
    token = request.headers.get("auth_token")   # change "-"  to  "_"
    result = {"token": token}
    return json.dumps(result)

if __name__ == "__main__":
    app.run("0.0.0.0", port=5000)
`
client_example.py
`
#  -*- coding: utf-8 -*-
import requests
from uuid import uuid4

"""client example"""

def example(url: str) -> None:
    token = uuid4().hex
    data = {"auth_token": token}   # change "-"  to  "_"
    r = requests.get(url=url, data=data)
    print(r.json())

if __name__ == "__main__":
    example("http://127.0.0.1:5000")
    example("http://127.0.0.1:6000")
`
run client_example.py  again.
result:
`
Connected to pydev debugger (build 172.4343.24)
{'token': '19ffcad928f844b2956b210d737342d2'}
{'token': None}

Process finished with exit code 0
`
[example link ](https://github.com/justonlyyo/py_projects/tree/master/bjoern_example)

**Comment by jonashaag** [comment]
This is a security feature, see https://github.com/jonashaag/bjoern/commit/9fd4d605cb7859632af7cc0f93b9a512510be66b
