### ISSUE TITLE
error python 3

### ISSUE THREAD

**Issue by vorlon001** [jonashaag/bjoern#126]
I FIX Error

TypeError: wsgi iterable items must be bytes (got 'str' object instead)
<class 'str'>

import bjoern

val = "2134213412341234123";

def hello_world(environ, start_response):
    status = '200 OK'
    res = val
    print(type(str(len(res))))
    response_headers = [
        ('Content-type','text/plain'),
        ('Content-Length',str(len(res)))]
    start_response(status, response_headers)
    return [res]
bjoern.run(hello_world, "127.0.0.1", 8000)

Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
debian 9

**Comment by jonashaag** [comment]
As the message says you have to return bytes not strings
