### ISSUE TITLE
Routing Feature

### ISSUE THREAD

**Issue by aheydar2** [jonashaag/bjoern#127]
Would you add routing feature to your awesome wsgi?
The only reason I am using Flask now is for its routing:

@app.route('/url/path/<var1><var2>')
def function f(var1, var2):
    pass

Then nginx+bjoern+app.py+js+html+css would be enough for many projects.
Thanks

**Comment by jonashaag** [comment]
Nope, that's out of scope for a web server, but I wrote a tiny routing framwork a few years ago: https://github.com/jonashaag/nano
