### ISSUE TITLE
BytesIO not supported

### ISSUE THREAD

**Issue by alexanderkunz** [jonashaag/bjoern#128]
When switching from the integrated bottle.py webserver to bjoern, I noticed that returning a BytesIO object apparently isn't supported. I didn't have that error before.

```
Client 40 hit errno 9
io.UnsupportedOperation: fileno

The above exception was the direct cause of the following exception:

SystemError: <built-in method close of _io.BytesIO object at 0x7f99bdf9d0a0> returned a result with an error set
```

**Comment by jonashaag** [comment]
Thanks for the report! It seems like we have to check for UnsupportedOperation explicitly, see https://github.com/benoitc/gunicorn/blob/06e252f23e53ff3f020ea5beaa13957d4a85e895/gunicorn/util.py#L509
