### ISSUE TITLE
400 bad request

### ISSUE THREAD

**Issue by monochromec** [jonashaag/bjoern#129]
Trying to get this hello world example to work on Bjoern, but failing miserably with "400 Bad Request" errors:

https://pastebin.com/1xQu5ZDg

What am I doing wrong? Thanks in advance for your help!

**Comment by jonashaag** [comment]
Works for me, maybe it's your client? Did you try curl?

**Comment by monochromec** [comment]
Thanks for the ultra-quick reply. curl works only on wsgi instance:
https://pastebin.com/x4Mxrg0X
But not on the web server instance:
https://pastebin.com/V0E0qzMR

nginx.conf:

https://pastebin.com/SJbyy8sr

Default site:

https://pastebin.com/DyB78RpC

Must be the interface config but I can't figure out why...

**Comment by jonashaag** [comment]
bjoern doesn't support the uWSGI interface, you'll have to use `proxy_pass`.

**Comment by monochromec** [comment]
Hi there,
I was just about to embark on a closer inspection of the server event loop in order to see how uwsgi requests are separated from ordinary http ones :-). Thanks for saving my time here - much appreciated!!
