### ISSUE TITLE
Graceful Connection Draining

### ISSUE THREAD

**Issue by CMCDragonkai** [jonashaag/bjoern#145]
I had a read of this issue: https://github.com/jonashaag/bjoern/issues/91

But I'm looking for a way to monitor the accept backlog and perform a graceful connection draining and termination.

Imagine you're running the bjoern Python HTTP server. I want to be able to send it a signal, which prevents it from accepting any new connections, while still attempting to complete all the requests on the backlog and then terminate. This is one option, the other option I need is to allow new connections to be accepted, but once the backlog is at 0, gracefully terminate. This allows me to maintain liveness while telling the clients to switch to another server.

If there was a way to monitor the backlog via the bjoern API that might work. But I suspect the signal handling will involve #91 being solved first.

**Comment by jonashaag** [comment]
Can’t you make this work with a load balancer or reverse proxy sitting in front? How do other Python webservers solve this?

**Comment by thefab** [comment]
I'm very interested in this issue too. Thanks @CMCDragonkai 

To take an example:

- I have an nginx reverse proxy listening to a TCP port and 8 bjoern processes listening on unix sockets
- the nginx reverse proxy (with an upstream configuration) acts as a load balancer for the 8 bjoern backend processes
- I want to hot-replace my bjoern backends
- I have an lua API in nginx to shutdown a backend route and to reopen it (great)
- But when I send SIGINT to bjoern, I think (I'm not sure about that) that bjoern gracefully process the current request but not its socket backlog (so I loose requests during my hot reload)

Of course, if I wait a lot after shutting down the backend route on nginx and before sending SIGINT to bjoern, it works. But I want an automated hot reload feature.

It is difficult to explain. @jonashaag: do you understand ?

**Comment by jonashaag** [comment]
Let me have a look at how active and pending connections are handled when sending ^C.

**Comment by jonashaag** [comment]
So, here's how Gunicorn works:

SIGINT shuts everything down momentarily.
SIGTERM waits for all active connections to finish, with a timeout (30 secs by default). It ignores the backlog though, and there doesn't seem to be a way to change that through configuration.

I agree that we should not throw away the backlog when doing a graceful shutdown.

Also I think it's fine to just stop bjoern without any kind of graceful shutdown for SIGINT (but not for SIGTERM).

Bjoern currently works as follows:

SIGINT waits for active connections to finish, without a timeout, and ignores the backlog.
SIGTERM simply terminates the program immediately.

So, going forward, my suggestion is we change Bjoern behaviour as follows:

- SIGTERM waits for active connections to finish, and the backlog to be empty (while still accepting new connections), with a timeout.
- SIGINT simply shuts down all connections immediately.

We can make the SIGTERM behaviour configurable, and allow for custom shutdown behaviours, by exporting some shutdown primitives from the C code.

**Comment by jonashaag** [comment]
Actually, let's continue discussing backlog draining in #91 as well!
