### ISSUE TITLE
what the deference among bjoern, meinheld and japronto ?

### ISSUE THREAD

**Issue by iamybj** [jonashaag/bjoern#150]
what the deference among bjoern, meinheld and japronto ?
I read that these 3 projects all say they are high performance.
which is best ?

**Comment by jonashaag** [comment]
Best for what? What are your requirements?

**Comment by iamybj** [comment]
I read that japronto use  uvloop and picohttpparser, much more fast than bjoern
but japronto is not just a WSGI server, and I dont like the code style of japronto
If bjoern can change from libev, http-parser to uvloop and picohttpparser for better performance ?

**Comment by jonashaag** [comment]
https://github.com/jonashaag/bjoern/issues/75#issuecomment-40882960

**Comment by iamybj** [comment]
Why not update http-parser to v2.8.1 ?

**Comment by jonashaag** [comment]
See #50

**Comment by iamybj** [comment]
I find most python programmers stand still.
That's why python only be used in some toy programmes, never be accepted by critical industry software fields.

**Comment by jonashaag** [comment]
Judging from your writing and your questions you’ve never run anything high performance in a professional environment. BTW Python is used for a lot of commercial software, e.g. Instagram, YouTube, Dropbox.

If you want high performance parsing, implement it in a non-Python library, not a a Python web server.
