### ISSUE TITLE
What about parsing http, json, xml, md5, rsa, mcrypt by coprocessor ?

### ISSUE THREAD

**Issue by iamybj** [jonashaag/bjoern#151]
As you know, GPU helps CPU processing video task.
And In old time, float point coprocessor helps CPU operate float-point computing.
Recently, messaging parsing and crypting passwords are widely used in internet industry.
If we can product a coprocessor that help CPU do these tasks ?

**Comment by jonashaag** [comment]
That’s really not a web server‘s job!
