### ISSUE TITLE
Can not install in Windown 10 ,Python 3.7

### ISSUE THREAD

**Issue by vpdinh** [jonashaag/bjoern#152]
Dear sirs, I can not install the library. Try both git clone and install setup.py and pypi with same error
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.15.26726\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DWANT_SENDFILE=1 -DWANT_SIGINT_HANDLING=1 -Ihttp-parser -I/usr/include/libev -IC:\Users\user\Anaconda3\include -IC:\Users\user\Anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.15.26726\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" /Tchttp-parser\http_parser.c /Fobuild\temp.win-amd64-3.6\Release\http-parser\http_parser.obj -std=c99 -fno-strict-aliasing -fcommon -fPIC -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -g
cl : Command line error D8021 : invalid numeric argument '/Wextra'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

**Comment by luketimothyjones** [comment]
So this actually appears to be an issue with `http-parser`. Go into http-parser's makefile and remove `-Wextra` from the CFLAGs on [line 55](https://github.com/nodejs/http-parser/blob/master/Makefile#L55), then try building.

**Comment by luketimothyjones** [comment]
Nevermind; this library relies on libev, which is Linux-only.
