### ISSUE TITLE
tests/test_wsgi_compliance.py broken for python 2.7?

### ISSUE THREAD

**Issue by risicle** [jonashaag/bjoern#158]
Tested on both linux and macos 10.13, `tests/test_wsgi_compliance.py` under python 2.7 raises

```
AssertionError: Environmental variable SERVER_PORT is not a string: <type 'unicode'> (value: u'5719800')
```

for me.

**Comment by risicle** [comment]
Oh, also, it would be useful if all the tests returned a non-zero exit status when they fail - this one doesn't.

**Comment by jonashaag** [comment]
Thanks for the report!
