### ISSUE TITLE
master broken on python 3

### ISSUE THREAD

**Issue by risicle** [jonashaag/bjoern#160]
I fear that https://github.com/jonashaag/bjoern/commit/eaca4b57d0b927ddf8af0244866f431ed90de3ce might have broken python 3 - following that, running e.g. `tests/keep-alive-behaviour.py` will only get me

```
ImportError: /nix/store/s6c6zqn37i9242ilb11ka6kcq6fvfqd3-python3.6-bjoern-2.2.3/lib/python3.6/site-packages/_bjoern.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyString_FromFormat
```

Works for 2.7 though.

**Comment by jonashaag** [comment]
@risicle Thanks for the report. I'll do a release
