### ISSUE TITLE
invalid chunked encoding with wsgi.file_wrapper

### ISSUE THREAD

**Issue by robehickman** [jonashaag/bjoern#165]
I'm doing some experiments with using bjoern to serve static files and it works fine using an iterator, but calling environ['wsgi.file_wrapper'] does not work, I get errno 104 in the terminal and an error about invalid chunked encoding in my browser.

```
import bjoern, os

def application(environ, start_response):
    file_path = 'test.jpg'
    block_size = 1024

    file_handle    = open(file_path, 'rb')
    
    # ----------
    status = '200 OK'
    response_headers = [('Content-type', 'image/jpeg')]

    start_response(status, response_headers)
# does not work:
    return environ['wsgi.file_wrapper'](file_handle, block_size)

# works:
    #return iter(lambda: file_handle.read(block_size), '')

bjoern.run(application, '0.0.0.0', 8070)
```

I added a content-length header with the file size, but this causes the python process to segfault when a request is made.

```
    file_size      = os.path.getsize(file_path)
    # added to response headers:
    ('Content-Length', str(file_size))
```

I am new to WSGI so may not be setting a required header, but have looked for examples of using the file_wrapper and don't see anything different.

Python 2.7, ubuntu 16.4 lts.

**Comment by robehickman** [comment]
Problem was my code, content-length header is required and the type of the length must be a string, where I assumed it would be an int. The following now works. There doesn't appear to be any notable difference in performance between using the iterator vs wsgi.file_wrapper though.

```
import bjoern, os

def application(environ, start_response):
    file_path = 'test.jpg'
    block_size = 1024

    file_handle    = open(file_path, 'rb')
    file_size      = os.path.getsize(file_path)
    
    # ----------
    status = '200 OK'
    response_headers = [('Content-type', 'image/jpeg'),
                                    ('Content-Length', str(file_size))]

    start_response(status, response_headers)
    return environ['wsgi.file_wrapper'](file_handle, block_size)
    
bjoern.run(application, '0.0.0.0', 8070)
```

**Comment by jonashaag** [comment]
Thanks for reporting this, even though you might've not adhered to the WSGI spec (not sure about that!) bjoern should never segfault. Will have a look

**Comment by robehickman** [comment]
No problem. I just looked at pep 333 and it says nothing about the types of
the response header, although the intent does seem to be a list of tuples
of two strings.

**Comment by jonashaag** [comment]
> it says nothing about the types of the response header

Funnily enough I just was like "that dude must be unable to read", had a quick look at both PEP 333 and 3333 and indeed I didn't find any explicit mention of the type of `header_value` O_O

**Comment by robehickman** [comment]
Lol.

Having docs stating things like using the file wrapper requires adding a
content length header manually would be useful. As far as i can see, the
wsgi spec does not state that this header must be added by the aplication
for the server.

**Comment by robehickman** [comment]
Just checked again, 333 implies that the client adding a content length
header is desireable but dosn't state that it is mandatory. I dont know how
other wsgi servers behave when using the file wrapper if content length
header is missing.

**Comment by robehickman** [comment]
Sorry about the delay, have been launching a book. I just updated to the latest version with pip, and am experiencing the same crash, I guess you have not pushed your change to pypi and that I need to install it from the repo?

**Comment by jonashaag** [comment]
Yes
