### ISSUE TITLE
Support for telemetry

### ISSUE THREAD

**Issue by Gufran** [jonashaag/bjoern#167]
Is there any plan to expose metrics? Something like statsd or prometheus sink should work for most people.
I can work on statsd or dogstatsd support if it hasn't been ruled out already.

**Comment by jonashaag** [comment]
No plan, can you specify what metrics you're interested in?

**Comment by Gufran** [comment]
Stats on connections. I'm thinking accepted, dropped, failed, active and queued but I'm sure there can be many other things people might want to see. I can start with basic instrumentation with above mentioned metrics and let people add to that if it makes sense.

**Comment by jonashaag** [comment]
Sounds useful. Design suggestions and PR welcome
