### ISSUE TITLE
Build scripts bug

### ISSUE THREAD

**Issue by BlackJohnny** [jonashaag/bjoern#170]
The current build scripts does not take into account the case when STATSD is not wanted.

Is there a "how to" setup the build environment?

PS: I have created some "quick and dirty" scripts to build a docker image for building the bjoern package. Is it worth fine-tuning it and create a pull request?

**Comment by jonashaag** [comment]
> The current build scripts does not take into account the case when STATSD is not wanted.

Then that's a bug, can you tell me more?

> PS: I have created some "quick and dirty" scripts to build a docker image for building the bjoern package. Is it worth fine-tuning it and create a pull request?

Definitely!
