### ISSUE TITLE
Can not install bjoern with RUN WANT_STATSD=yes make all

### ISSUE THREAD

**Issue by totti4Life** [jonashaag/bjoern#184]
I try to install it inside a docker container.
simply: `make all` works
for the statsd flag I get the fallowing output:

tep 11/11 : RUN WANT_STATSD=yes make all
 ---> Running in c3fb86a928a7
 ->  cc -I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu/python2.7 -I . -I bjoern -I http-parser -I statsd-c-client -D WANT_SIGINT_HANDLING -D WANT_SIGNAL_HANDLING -D SIGNAL_CHECK_INTERVAL=0.1 -D WANT_STATSD -std=c99 -fno-strict-aliasing -fcommon -fPIC -Wall -c bjoern/filewrapper.c -o build/filewrapper.o
In file included from bjoern/filewrapper.c:2:0:
bjoern/py2py3.h:67:12: warning: ‘_PEP3333_String_CompareWithASCIIString’ defined but not used [-Wunused-function]
 static int _PEP3333_String_CompareWithASCIIString(PyObject *o, const char *c_str)
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bjoern/py2py3.h:57:18: warning: ‘_PEP3333_String_Concat’ defined but not used [-Wunused-function]
 static PyObject *_PEP3333_String_Concat(PyObject *l, PyObject *r)
                  ^~~~~~~~~~~~~~~~~~~~~~
bjoern/py2py3.h:46:18: warning: ‘_PEP3333_String_FromLatin1StringAndSize’ defined but not used [-Wunused-function]
 static PyObject* _PEP3333_String_FromLatin1StringAndSize(const char* data, Py_ssize_t len)
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ->  cc -I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu/python2.7 -I . -I bjoern -I http-parser -I statsd-c-client -D WANT_SIGINT_HANDLING -D WANT_SIGNAL_HANDLING -D SIGNAL_CHECK_INTERVAL=0.1 -D WANT_STATSD -std=c99 -fno-strict-aliasing -fcommon -fPIC -Wall -c bjoern/request.c -o build/request.o
In file included from bjoern/request.c:5:0:
bjoern/request.c: In function ‘_initialize_request_module’:
bjoern/request.c:404:88: warning: format ‘%i’ expects argument of type ‘int’, but argument 2 has type ‘PyObject * {aka struct _object *}’ [-Wformat=]
         PyDict_SetItemString(wsgi_base_dict, "SERVER_PORT", _PEP3333_String_FromFormat("%i", server_info->port));
                                                                                        ^
bjoern/py2py3.h:43:61: note: in definition of macro ‘_PEP3333_String_FromFormat’
 #define _PEP3333_String_FromFormat(...) PyString_FromFormat(__VA_ARGS__)
                                                             ^~~~~~~~~~~
 ->  cc -I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu/python2.7 -I . -I bjoern -I http-parser -I statsd-c-client -D WANT_SIGINT_HANDLING -D WANT_SIGNAL_HANDLING -D SIGNAL_CHECK_INTERVAL=0.1 -D WANT_STATSD -std=c99 -fno-strict-aliasing -fcommon -fPIC -Wall -c bjoern/statsd_tags.c -o build/statsd_tags.o
 ->  cc -I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu/python2.7 -I . -I bjoern -I http-parser -I statsd-c-client -D WANT_SIGINT_HANDLING -D WANT_SIGNAL_HANDLING -D SIGNAL_CHECK_INTERVAL=0.1 -D WANT_STATSD -std=c99 -fno-strict-aliasing -fcommon -fPIC -Wall -c bjoern/common.c -o build/common.o
In file included from bjoern/common.c:2:0:
bjoern/py2py3.h:67:12: warning: ‘_PEP3333_String_CompareWithASCIIString’ defined but not used [-Wunused-function]
 static int _PEP3333_String_CompareWithASCIIString(PyObject *o, const char *c_str)
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bjoern/py2py3.h:57:18: warning: ‘_PEP3333_String_Concat’ defined but not used [-Wunused-function]
 static PyObject *_PEP3333_String_Concat(PyObject *l, PyObject *r)
                  ^~~~~~~~~~~~~~~~~~~~~~
bjoern/py2py3.h:46:18: warning: ‘_PEP3333_String_FromLatin1StringAndSize’ defined but not used [-Wunused-function]
 static PyObject* _PEP3333_String_FromLatin1StringAndSize(const char* data, Py_ssize_t len)
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ->  cc -I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu/python2.7 -I . -I bjoern -I http-parser -I statsd-c-client -D WANT_SIGINT_HANDLING -D WANT_SIGNAL_HANDLING -D SIGNAL_CHECK_INTERVAL=0.1 -D WANT_STATSD -std=c99 -fno-strict-aliasing -fcommon -fPIC -Wall -c bjoern/_bjoernmodule.c -o build/_bjoernmodule.o
 ->  cc -I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu/python2.7 -I . -I bjoern -I http-parser -I statsd-c-client -D WANT_SIGINT_HANDLING -D WANT_SIGNAL_HANDLING -D SIGNAL_CHECK_INTERVAL=0.1 -D WANT_STATSD -std=c99 -fno-strict-aliasing -fcommon -fPIC -Wall -c bjoern/portable_sendfile.c -o build/portable_sendfile.o
 ->  cc -I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu/python2.7 -I . -I bjoern -I http-parser -I statsd-c-client -D WANT_SIGINT_HANDLING -D WANT_SIGNAL_HANDLING -D SIGNAL_CHECK_INTERVAL=0.1 -D WANT_STATSD -std=c99 -fno-strict-aliasing -fcommon -fPIC -Wall -c bjoern/server.c -o build/server.o
In file included from bjoern/server.c:20:0:
bjoern/py2py3.h:67:12: warning: ‘_PEP3333_String_CompareWithASCIIString’ defined but not used [-Wunused-function]
 static int _PEP3333_String_CompareWithASCIIString(PyObject *o, const char *c_str)
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bjoern/py2py3.h:57:18: warning: ‘_PEP3333_String_Concat’ defined but not used [-Wunused-function]
 static PyObject *_PEP3333_String_Concat(PyObject *l, PyObject *r)
                  ^~~~~~~~~~~~~~~~~~~~~~
bjoern/py2py3.h:46:18: warning: ‘_PEP3333_String_FromLatin1StringAndSize’ defined but not used [-Wunused-function]
 static PyObject* _PEP3333_String_FromLatin1StringAndSize(const char* data, Py_ssize_t len)
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ->  cc -I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu/python2.7 -I . -I bjoern -I http-parser -I statsd-c-client -D WANT_SIGINT_HANDLING -D WANT_SIGNAL_HANDLING -D SIGNAL_CHECK_INTERVAL=0.1 -D WANT_STATSD -std=c99 -fno-strict-aliasing -fcommon -fPIC -Wall -c bjoern/wsgi.c -o build/wsgi.o
In file included from bjoern/wsgi.c:4:0:
bjoern/py2py3.h:67:12: warning: ‘_PEP3333_String_CompareWithASCIIString’ defined but not used [-Wunused-function]
 static int _PEP3333_String_CompareWithASCIIString(PyObject *o, const char *c_str)
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bjoern/py2py3.h:57:18: warning: ‘_PEP3333_String_Concat’ defined but not used [-Wunused-function]
 static PyObject *_PEP3333_String_Concat(PyObject *l, PyObject *r)
                  ^~~~~~~~~~~~~~~~~~~~~~
bjoern/py2py3.h:46:18: warning: ‘_PEP3333_String_FromLatin1StringAndSize’ defined but not used [-Wunused-function]
 static PyObject* _PEP3333_String_FromLatin1StringAndSize(const char* data, Py_ssize_t len)
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ->  cc -I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu/python2.7 -I . -I bjoern -I http-parser -I statsd-c-client -D WANT_SIGINT_HANDLING -D WANT_SIGNAL_HANDLING -D SIGNAL_CHECK_INTERVAL=0.1 -D WANT_STATSD -std=c99 -fno-strict-aliasing -fcommon -fPIC -Wall -L/usr/lib/python2.7/config-x86_64-linux-gnu -L/usr/lib -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions -l ev -shared -fcommon http-parser/http_parser.o statsd-c-client/statsd-client.o build/filewrapper.o build/request.o build/statsd_tags.o build/common.o build/_bjoernmodule.o build/portable_sendfile.o build/server.o build/wsgi.o -o build/_bjoern.so
/usr/bin/ld: statsd-c-client/statsd-client.o: relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
make: *** [_bjoernmodule] Error 1
Makefile:62: recipe for target '_bjoernmodule' failed

Altough as I see the -fPIC  flag is set.

**Comment by jonashaag** [comment]
Could it be that you compiled http-parser without `-fPIC`? Can you say exact steps to reproduce? (What Docker image and exact commands you typed)

**Comment by totti4Life** [comment]
Thank you for your fast reply.
I did nothing special. I get the same error in Ubuntu without installing it inside docker.
I cloned the repo from github. Then updated the submodules. Entered the "bjoern" directory and run

**Comment by jonashaag** [comment]
Thanks for the report, should work now! Copy and paste error.

**Comment by totti4Life** [comment]
It still gives me the linking error

cc -I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu/python2.7 -I . -I bjoern -I http-parser -I statsd-c-client -D WANT_SIGINT_HANDLING -D WANT_SIGNAL_HANDLING -D SIGNAL_CHECK_INTERVAL=0.1 -D WANT_STATSD -std=c99 -fno-strict-aliasing -fcommon -fPIC -Wall -L/usr/lib/python2.7/config-x86_64-linux-gnu -L/usr/lib -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions -l ev -shared -fcommon http-parser/http_parser.o statsd-c-client/statsd-client.o build/filewrapper.o build/request.o build/common.o build/statsd_tags.o build/portable_sendfile.o build/_bjoernmodule.o build/server.o build/wsgi.o -o build/_bjoern.so
/usr/bin/ld: statsd-c-client/statsd-client.o: relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make: *** [Makefile:63: _bjoernmodule] Error 1

**Comment by jonashaag** [comment]
Remove any .o files from the statsd folder

**Comment by totti4Life** [comment]
Thank you. It worked that way inside the container where Debian 10 is running.
But under Ubuntu 19 (tested on my PC) and Ubuntu 18 (tested on a Hetzner server) a strange error occurs. I know it is not related to bjoern but I don't know what is the reason. The methods from <ev.h> are not recognized although the header is included (Because libev-dev is installed) 

cc -I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu/python2.7 -I . -I bjoern -I http-parser -I statsd-c-client -D WANT_SIGINT_HANDLING -D WANT_SIGNAL_HANDLING -D SIGNAL_CHECK_INTERVAL=0.1 -D WANT_STATSD -std=c99 -fno-strict-aliasing -fcommon -fPIC -Wall -L/usr/lib/python2.7/config-x86_64-linux-gnu -L/usr/lib -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions -l ev -shared -fcommon http-parser/http_parser.o statsd-c-client/statsd-client.o build/filewrapper.o build/request.o build/common.o build/statsd_tags.o build/portable_sendfile.o build/_bjoernmodule.o build/server.o build/wsgi.o -o build/_bjoern.so
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "bjoern.py", line 3, in <module>
    import _bjoern
ImportError: /home/sandor/Work/Wexel/Repos/TestBjoern/bjoern/build/_bjoern.so: undefined symbol: ev_timer_start
