### ISSUE TITLE
WANT_STATSD make all build succeeds, but import doesn't work in python3

### ISSUE THREAD

**Issue by sith0008** [jonashaag/bjoern#187]
Hi, I managed to build Bjoern using make all (but python setup.py doesn't work as per #185 ) and I had to manually copy the bjoern.py and _bjoern.so files to the python lib directory. Is that supposed to be the case? because when I checked my environment variables, the paths to the files are not added to the PATH

Also, I could start a python2 shell and import bjoern but when I tried using python3, the import fails because of this error:

`ImportError: dynamic module does not define module export function (PyInit__bjoern)`

Does make all only work for python2?

[Context: I'm building it in docker, using the python:3.7-slim image which is based on Debian]

**Comment by jonashaag** [comment]
Can you please show the exact commands you are using

**Comment by jonashaag** [comment]
Also try using `make PYTHON=3` for building for the non-system-default Python version

**Comment by sith0008** [comment]
Thanks for your reply! I tried `make all PYTHON=python3` and I managed to import bjoern from a python3 shell! But the same issue of having to copy the files manually to /usr/local/lib/python3 remains. For the steps to reproduce, after cloning the bjoern repository and the http-parser and statsd-c-client repository, i ran 
`WANT_STATSD=yes WANT_STATSD_TAGS=yes PYTHON=python3 make all`

**Comment by jonashaag** [comment]
I don't understand what you mean by manually copying. Obviously you have to put the files at some place where the Python interpreter can find them, and if you're not starting the interpreter from the bjoern folder it means they have to be somewhere else in PYTHONPATH.

**Comment by sith0008** [comment]
alright, got it thank you!
