### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by AlexProfi** [jonashaag/bjoern#188]
Hello. When using 3.10 or 3.0.1 versions  I get Segmentaion fault  error, when using unix sockets.
 In tcp sockets everything ok

I run this code

```
import bjoern
sock_name = "/home/alex/sites/mezzanine/etk62/etk62.sock"
sock_path = "unix:%s" %sock_name
# start bjoern on unix socket
bjoern.run(application, sock_path)
```

There is my config

bcrypt==3.1.7
bjoern==3.1.0
bleach==3.1.0
certifi==2019.6.16
cffi==1.14.0
chardet==3.0.4
cryptography==2.9.2
Django==1.6.11
enum34==1.1.10
fabric==2.5.0
filebrowser-safe==0.5.0
future==0.9.0
grappelli-safe==0.5.2
idna==2.8
invoke==1.4.1
ipaddress==1.0.23
Mezzanine==3.0.9
MySQL-python==1.2.5
oauthlib==3.0.2
paramiko==2.7.1
Pillow==6.1.0
psycopg2==2.8.3
pycparser==2.20
PyNaCl==1.4.0
python-memcached==1.59
pytz==2019.1
requests==2.22.0
requests-oauthlib==1.2.0
six==1.12.0
tzlocal==1.0
urllib3==1.25.3
webencodings==0.5.1
(etk62) alex@etk62:~/mezzanine/etk62$ python
Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 

How to solve it?

**Comment by jonashaag** [comment]
Hm, can you try upgrading to the latest Python 2.7.x? If that doesn't help, can you get a traceback using `gdb` or `lldb`?

**Comment by AlexProfi** [comment]
I check on another computer with ubuntu 18.04 and python 2.7.17 everything is ok
