### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by AlexProfi** [jonashaag/bjoern#189]
Is it possible to make bjoern multithreaded or mutiprocess
I ran manage.py runserver and saw that load of Python 164%

When I try to load product site, that works on bjoern, with ab I don't see more than Python 93% load of cpu. I ran ab -n 100000  -c 400 -k

**Comment by jonashaag** [comment]
You can use multiple processes with receive steering, or fork multiple processes, or use a reverse proxy in front of bjoern.

**Comment by AlexProfi** [comment]
Thanks. I found example in tests.
