### ISSUE TITLE
wiki installation details not working on Ubuntu 18

### ISSUE THREAD

**Issue by humblewolf** [jonashaag/bjoern#190]
I am using python 3.6 on Ubuntu 18

I tried installing python headers mentioned in wiki using:
apt-get install python2-dev
but it did not worked as this apt package was not available.
-----------
apt-get install python-dev
package was available but pip install failed
-----------
What worked for me was 
apt-get install python3.6-dev
-----------

I guess we may need to update wiki  :)

**Comment by jonashaag** [comment]
The Wiki is community maintained (that’s more or less to es definition of what’s a Wiki), so feel free to do the changes yourself :-)
