### ISSUE TITLE
> It always works as a WSGI server (which is a special kind of HTTP server)

### ISSUE THREAD

**Issue by jonashaag** [jonashaag/bjoern#193]
> It always works as a WSGI server (which is a special kind of HTTP server)

Hmm....

This is my `wsgi.py`

```python
import os
from app.core import create_app


app = create_app()

if __name__ == '__main__':
    #app.run(debug=True)
    import bjoern
    port = os.getenv('BIND_PORT', '8000')

    if not port or not port.isdigit():
        raise RuntimeError('Socket for bind not found.')

    bjoern.run(app, host='localhost', port=int(port))
```

this is a part of nginx config

```config
    location ~ ^/(?<app>\w+)/(?<app_uri>.*) {
        include uwsgi_params;
        uwsgi_param SCRIPT_NAME /$app;
        uwsgi_param PATH_INFO /$app_uri;
        uwsgi_pass localhost:8000;

        #access_log /var/log/nginx/app/$app.log;
        error_log  /var/log/nginx/app/errors.log warn;
    }
```

And I'm getting a 400 error code. Any ideas why?

// It works if use `proxy_pass` instead of `uwsgi_pass` but `SCRIPT_NAME` in this case is missed.

_Originally posted by @ak04nv in https://github.com/jonashaag/bjoern/issues/91#issuecomment-712716353_

**Comment by jonashaag** [comment]
uwsgi has its own protocol that has very little to do with WSGI and can only be used with uwsgi.

**Comment by ak04nv** [comment]
FYI, [wsgi and uwsgi are both protocols](https://stackoverflow.com/questions/7739810/wsgi-vs-uwsgi-with-nginx#:~:text=WSGI%20and%20uwsgi%20both%20ARE,pure%20HTTP%20can%20not%20provide.&text=uWSGI%20is%20a%20server%20and,protocol%20with%20the%20uWSGI%20server)

But as I understand bjoern supports wsgi and http only.
Now it's clear.

**Comment by jonashaag** [comment]
I know, that's why I said

> uwsgi has its own protocol

:-) You'll not find a lot of (if any!) other uwsgi protocol implementations except for the uwsgi server itself. I'm not sure it's even properly documented and standardised.

**Comment by ak04nv** [comment]
@jonashaag 
Thank you for the details :) Sorry for waste your time.
I'm trying to find a way to using bjoern as wsgi server for bulk python applications. Still no result. :-/

**Comment by jonashaag** [comment]
You could just start multiple bjoern servers and make nginx load balance between them, or use receive steering (search this repo for examples)

**Comment by ak04nv** [comment]
This is exactly what I'm trying to do. But as I understood I need to use only `proxy_pass` directive in nginx config. In this case `SCRIPT_NAME` parameter is lost.

**Comment by jonashaag** [comment]
Hm... yeah I remember there were some problems with nginx and `SCRIPT_NAME`... maybe you can simply pass the value through a custom header and add a WSGI wrapper application that fixes `SCRIPT_NAME`, like so:

```
def fix_script_name_wrapper(app):
	def fix_script_name(environ, start_response):
		environ['SCRIPT_NAME'] = environ['HTTP_X_AK04NV_SCRIPT_NAME']
		return app(environ, start_response)
	return fix_script_name

app = fix_script_name_wrapper(app)
```

**Comment by ak04nv** [comment]
Sure it possible to add a middleware layer like [this](https://github.com/pallets/werkzeug/blob/master/src/werkzeug/wrappers/base_request.py#L571) and fix this issue. But I have to do this for all applications. It is not a good way.
Some frameworks understand the `HTTP_X_SCRIPT_NAME` header but not all.
