### ISSUE TITLE
Broken pipe error(errno 32) is looping for unix sockets

### ISSUE THREAD

**Issue by supratikchatterjee16** [jonashaag/bjoern#196]
While testing an application there seems to be an issue that keeps arising and fills my error logs by
adding the following errors : 

![image](https://user-images.githubusercontent.com/25512106/99941962-e6788580-2d94-11eb-9b1d-a3acc07e944a.png)

My code : 
```python
def deploy():
	import os
	import app
	import bjoern
	import signal
	import socket
	host = '0.0.0.0'
	# port = 8766 # W(87)B(66) for Workbench
	NUM_WORKERS = 10
	worker_pids = []
	socket_path = './something.sock'
	sock = socket.socket(socket.AF_UNIX)
	sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
	sock.settimeout(1) # Assumption seconds
	sock.bind(socket_path)
	sock.listen(1024)
	os.chmod(socket_path, 0o666)
	try:
		print('Attempting run : ')
		bjoern.server_run(sock, app.create())
	except KeyboardInterrupt:
		print('Eliminating Unix Socket')
		os.unlink(sock.getsockname())
		sock.close()
	except Exception as e:
		print(e)
```

I recreate the error by running the program and then continuously refreshing the page, 
but it starts doing this automatically as well.

The line being executed(permalink):

https://github.com/jonashaag/bjoern/blob/f50e514885c10793ec7cfce845015ac17e82ef69/bjoern/server.c#L521

It isn't hanging up as you intended it to be, I think.

**Comment by jonashaag** [comment]
Does this also happen if you use he built in socket initialization? What about port based sockets?

**Comment by supratikchatterjee16** [comment]
It does not happen with the TCP port based sockets.
But is happening even with the inbuilt Unix sockets intialization.

```python
# Tested lines
bjoern.run(app.create(), 'localhost', 8000, reuse_port = True)
bjoern.run(app.create(), 'unix:'+os.path.join(os.getcwd(), 'workbench.sock'))
```

**Comment by jonashaag** [comment]
Can't reproduce, can you try with this app? How exactly are you sending the request? Can you try with cURL?

```
def app(environ, start_response):
    start_response('200 OK', [])
    return ''
```

```
curl -v --unix-socket ./something.sock /someurl
```

**Comment by supratikchatterjee16** [comment]
I modified the test scripts a bit to match the situation, it is recurring, albeit slowly this time :

The script : 

```shell
for i in {1..50}
do
	curl -v --unix-socket /media/supratik/Data/Space/TCS/internal/projects/bjoern_testing/something.sock hello & kill -9 "$(pgrep curl)"
done
```

The program : 

```python
import os
import bjoern

def app(environ, start_response):
	# adding proccessing overhead
	ctr = 0
	for i in range(0, 10000):
		ctr2 = 0
		for j in range(0, 10000):
			ctr2 += j
		ctr += ctr2
	start_response('200 OK', [('Content-Type','text/plain')])
	return [bytes(str(ctr), 'utf-8')]
try:
	bjoern.run(app, 'unix:'+os.path.join(os.getcwd(), 'something.sock'))
except KeyboardInterrupt:
	print('exit')
except Exception as e:
	print(e)
```

CLI output : 

![image](https://user-images.githubusercontent.com/25512106/100047694-1b3e1880-2e39-11eb-9e57-68dade33ab7b.png)

**Comment by jonashaag** [comment]
Umm ok but if you are killing the client then no wonder bjoern reports that it had gone.

**Comment by supratikchatterjee16** [comment]
Yes.

Shouldn't the server also be killing the connection and consequently the loop, instead of looping over it, reporting it several times,
blocking a thread permanently. 

This keeps recurring, increasing CPU usage times.

I think you implemented a method to break the loop, in case of a critical failure(in this case EPIPE) in the transaction, in the following lines : 
https://github.com/jonashaag/bjoern/blob/f50e514885c10793ec7cfce845015ac17e82ef69/bjoern/server.c#L522-L525
but it isn't breaking in case of the UNIX socket. The error log above is for executing the shell script once, which stopped after a while.

In case of the flask app/browser facing server with the Unix socket, it doesn't stop.

Closing a tab while loading seems to induce this behavior.

On the TCP stream socket, it works exactly the way you've coded it to.

**Comment by jonashaag** [comment]
Aaah, didn’t understand that was the case for you. Ok, will try to guess what’s going on or reproduce it with your code.

**Comment by supratikchatterjee16** [comment]
If there is any way I could help out, please let me know.

**Comment by jonashaag** [comment]
From a very quick look at the code only I think the way send errors are handled is incorrect.

Here there is no error handling at all 😱
https://github.com/jonashaag/bjoern/blob/f50e514885c10793ec7cfce845015ac17e82ef69/bjoern/server.c#L383

And I think here there should be 3 rather than 2 statuses (EOF, not EOF, and error)

https://github.com/jonashaag/bjoern/blob/f50e514885c10793ec7cfce845015ac17e82ef69/bjoern/server.c#L403

If you want you can try to change the code using `read_state` instead of `bool`

https://github.com/jonashaag/bjoern/blob/f50e514885c10793ec7cfce845015ac17e82ef69/bjoern/server.c#L48

**Comment by supratikchatterjee16** [comment]
I'll try it out. Will create a PR if it works out.

**Comment by jimduden6804** [comment]
Hello,
we use bjoren in our systems an see a similar problem.
Will this be realeased any time soon? 

Thank you very much :)

**Comment by wravoc** [comment]
The fix was only for Linux only, not including BSD, and is over two years old for such a big problem handling socket looping upon web tab close. Not really suitable for production internet.

Maybe @jonashaag can find a suitable replacement to take over this repository. Remove socket binding for everything but Linux?
