### ISSUE TITLE
Need some example working out of the box

### ISSUE THREAD

**Issue by 108806** [jonashaag/bjoern#201]
Lines in docs like `"bjoern.run(wsgi_application, host, port)"` Are unclear to me, I don't know what file should be passed as wsgi_application, what should be inside of this file, etc. 
Some simple example working out of the box after just one $git clone would crystalize a huge ammount of really vogue things for me.

**Comment by jonashaag** [comment]
Added a simple Flask example to the README, does that help? https://github.com/jonashaag/bjoern/blob/master/README.rst#usage

**Comment by 108806** [comment]
Awesome, its clear enough now
