### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by himadriganguly** [jonashaag/bjoern#205]
Cannot install using `pip install bjoern` on **python3**.

**Comment by phacic** [comment]
hi how was this one resolved. Am facing it too

**Comment by himadriganguly** [comment]
@phacic This has not been resolved but the maintainer closed the issue.

**Comment by phacic** [comment]
@himadriganguly [here is what worked for me](https://github.com/jonashaag/bjoern/issues/211#issuecomment-806508471).
