### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by phacic** [jonashaag/bjoern#211]
pip log

` Building wheels for collected packages: bjoern
    Building wheel for bjoern (setup.py): started
    Building wheel for bjoern (setup.py): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-0gx_r4bx/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-0gx_r4bx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ailnxvdb
         cwd: /tmp/pip-req-build-0gx_r4bx/
    Complete output (22 lines):
    running bdist_wheel
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    copying bjoern.py -> build/lib.linux-x86_64-3.6
    warning: build_py: byte-compiling is disabled, skipping.
    
    running build_ext
    building '_bjoern' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/http-parser
    creating build/temp.linux-x86_64-3.6/bjoern
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DSIGNAL_CHECK_INTERVAL=0.1 -DWANT_SIGNAL_HANDLING=yes -DWANT_SIGINT_HANDLING=yes -Ihttp-parser -Istatsd-c-client -I/usr/include/libev -I/opt/local/include -I/usr/local/include/python3.6m -c http-parser/http_parser.c -o build/temp.linux-x86_64-3.6/http-parser/http_parser.o -std=c99 -fno-strict-aliasing -fcommon -fPIC -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -g
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DSIGNAL_CHECK_INTERVAL=0.1 -DWANT_SIGNAL_HANDLING=yes -DWANT_SIGINT_HANDLING=yes -Ihttp-parser -Istatsd-c-client -I/usr/include/libev -I/opt/local/include -I/usr/local/include/python3.6m -c bjoern/_bjoernmodule.c -o build/temp.linux-x86_64-3.6/bjoern/_bjoernmodule.o -std=c99 -fno-strict-aliasing -fcommon -fPIC -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -g
    In file included from bjoern/wsgi.h:2,
                     from bjoern/_bjoernmodule.c:3:
    bjoern/request.h:4:10: fatal error: ev.h: No such file or directory
     #include <ev.h>
              ^~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
    ERROR: Failed building wheel for bjoern
    Running setup.py clean for bjoern
  Failed to build bjoern
`

any help?

**Comment by phacic** [comment]
after adding this to my dockerfile it worked

>RUN apt-get update && apt-get install -y --no-install-recommends libev-dev git  \
	&& rm -rf /var/lib/apt/lists/*t \
    && cd /usr/src \
    && git clone https://github.com/jonashaag/bjoern \
    && cd bjoern \
    && git submodule update --init \
    && python setup.py install \
    && pip install poetry \
    && poetry config virtualenvs.create false \
    && poetry install

**Comment by huasmc** [comment]
Installation is failing

`pip-install-tw1v9wl0\bjoern_27a00f805635469cafe8d1156c529a54\setup.py", line 26, in <module>
        SOURCE_FILES.remove('statsd-c-client/statsd-client.c')
    ValueError: list.remove(x): x not in list`

**Comment by FoxNerdSaysMoo** [comment]
If you are using Arch, `sudo pacman -Sy libev` fixes the problem

**Comment by alex-arica** [comment]
In the installation section in README file, can we mention that we need libev-dev to be installed?
We could give an example on Debian based distros and on Arch?

For example:
"
Please make sure libev or libdev-dev is installed on your linux distro.

For Debian:
```
apt-get install -y --no-install-recommends libev-dev
```


For Arch:
```
pacman -Sy libev
```
"

**Comment by jonashaag** [comment]
Happy to merge a PR that doesn't duplicate the instructions that are already in the wiki.

**Comment by getcake** [comment]
Just wanted to add the installing python3-dev solved this issue for me (after I had already installed libev-dev)
