### ISSUE TITLE
Bjoern port reuse with socket error: "module 'socket' has no attribute 'SO_REUSEPORT'"

### ISSUE THREAD

**Issue by shaowei-su** [jonashaag/bjoern#217]
Python version: 3.6.12
Linux Kernel: Linux 4.4.0-96-generic x86_64
Error stacktrace:
```
    bjoern.run(self.app, '0.0.0.0', port, reuse_port=True)
  File "/home/default_user/.conda/envs/user/lib/python3.6/site-packages/bjoern.py", line 85, in run
    listen(*args, **kwargs)
  File "/home/default_user/.conda/envs/user/lib/python3.6/site-packages/bjoern.py", line 64, in listen
    listen_backlog=listen_backlog)
  File "/home/default_user/.conda/envs/user/lib/python3.6/site-packages/bjoern.py", line 29, in bind_and_listen
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEPORT, 1)
AttributeError: module 'socket' has no attribute 'SO_REUSEPORT'
```

Similar discussion: https://community.intel.com/t5/Intel-Distribution-for-Python/AttributeError-module-socket-has-no-attribute-SO-REUSEPORT/m-p/1198400

**Comment by nhoad** [comment]
The implication here is that your OS doesn't have support for `SO_REUSEPORT`. This is either an issue with your build of Python or Linux.

**Comment by shaowei-su** [comment]
Right we have to disable this feature for now due to various Python & Linux distributions involved. 
Closing the issue for now and thanks for the explanations.
