### ISSUE TITLE
SERVER_PORT and SERVER_HOST values are incorrect

### ISSUE THREAD

**Issue by trollfot** [jonashaag/bjoern#218]
With this code

```
if __name__ == "__main__":
    import bjoern

    bjoern.run(app, host="localhost", port=8000)
```

I get : 
'SERVER_NAME': '127.0.0.1',
'SERVER_PORT': '1596915664'

Each time I run my server, whatever the initial values are, I get a random int as a port. What's going on ?

**Comment by jonashaag** [comment]
Uh oh. This was introduced in #123. Can you try to replace `%i` here with `%S`?

https://github.com/jonashaag/bjoern/blob/efb73524a232d200d27bca31bc329275b3f8c2c7/bjoern/request.c#L404

**Comment by jonashaag** [comment]
As for `SERVER_NAME`, I'm not sure what should be reported. What do other servers do?

**Comment by trollfot** [comment]
I don't think there's anything explicit about the SERVER_NAME. My understand would be that the SERVER_NAME + SERVER_PORT could be the HTTP_HOST

```
'HTTP_HOST': 'localhost:8000',
'SERVER_NAME': '127.0.0.1',
'SERVER_PORT': '-845819952'
```

In this case, this is what i get. If we forget about the port situation, I would expect SEVER_NAME to be "localhost", for consistency. Maybe my understanding is wrong, which is a strong possibility either !

I'll test the %S for the port and make a PR accordingly, if it's right.
