### ISSUE TITLE
Build fails on M1 Mac using Homebrew

### ISSUE THREAD

**Issue by ijs-octo** [jonashaag/bjoern#226]
Hi,

Building on an M1 Mac fails to find the libev headers when libev was installed via Homebrew.

The reason for this is that, on M1, Homebrew installs headers into /opt/homebrew/include, which is not in the search path specified in the setup.py file.

The easy fix was to add the M1 homebrew path to the set of includes (which does seem to have worked), but is there a better way? I'm not really familiar with how Python handles building native libraries -- for instance is there a recommended way to detect an M1 build and only add this extra folder in that case?

**Comment by sskorol** [comment]
You can use the following option:
```shell
pip3 install --global-option=build_ext --global-option="-I/opt/homebrew/include" bjoern
```

**Comment by ijs-octo** [comment]
Thanks for the suggestion, it's definitely better than manually editing the setup.py file!

Maybe adding something like this to the installation guide would be worthwhile? (Given that Homebrew is specifically called out for macOS)

**Comment by jonashaag** [comment]
Thanks, make a PR to add it here? https://github.com/jonashaag/bjoern/blob/master/setup.py#L33

**Comment by ijs-octo** [comment]
A pull request to add the header path has been submitted as PR #228. It would also be good to add the suggestion for local modifications to the header path on the wiki -- I'd be happy to look at that if you can let me know how you'd like the change to be proposed.

**Comment by usul83** [comment]
Hi, the fixes here work for finding `ev.h`, however I then run into another error: 
    `ld: library not found for -lev
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      error: command '/usr/bin/clang' failed with exit code 1`

**Comment by ijs-octo** [comment]
"It works for me"...

Where is your libev library? For me:

```
$ find /opt/homebrew -name 'libev.dylib' -print
/opt/homebrew/lib/libev.dylib
/opt/homebrew/Cellar/libev/4.33/lib/libev.dylib
```

Also, are you using a pip/python installed by Homebrew?

**Comment by usul83** [comment]
`/opt/homebrew/lib/libev.dylib`
`/opt/homebrew/Cellar/libev/4.33/lib/libev.dylib`
I'm trying to install in a python venv, created using a python installed with homebrew. That's a good clue, I'll try installing python in a different way.

**Comment by jonashaag** [comment]
Please try latest master

**Comment by usul83** [comment]
that works, cheers
