### ISSUE TITLE
Build bjoern error in mac m1 with command `pip3 install --global-option=build_ext --global-option="-I/opt/homebrew/include" bjoern`

### ISSUE THREAD

**Issue by yukar1z0e** [jonashaag/bjoern#229]
When I tried the command `pip3 install --global-option=build_ext --global-option="-I/opt/homebrew/include" bjoern` to build bjoern , it crashed out with the erroers below.
<img width="570" alt="截屏2022-05-07 15 56 27" src="https://user-images.githubusercontent.com/44317939/167244975-e2737f76-4948-405a-ac22-9c7bb0de1779.png">

**Comment by jonashaag** [comment]
https://github.com/jonashaag/bjoern/wiki/Installation

**Comment by zjpzzZ** [comment]
My mac m1 has installed libev and gcc,but it also cant work
<img width="630" alt="image" src="https://user-images.githubusercontent.com/48352060/167254875-a0e7d357-38a5-4a13-a7eb-5f41b755ee5f.png">

**Comment by jonashaag** [comment]
https://github.com/jonashaag/bjoern/issues/226

**Comment by HK69s** [comment]
You can use the following command：`pip3 install --global-option=build_ext --global-option="-I/opt/homebrew/include" --global-option="-L/opt/homebrew/lib" bjoern`

**Comment by synchronizing** [comment]
The following works on M2 after `brew install libev`:

```
LDFLAGS="-L$(brew --prefix libev)/lib" CFLAGS="-I$(brew --prefix libev)/include" pip install bjoern
```

Homebrew v3.0.0 modified the default prefix depending on Intel/Silicon, see [here](https://stackoverflow.com/a/71186857/1305461). These changes can be added to the repo [here](https://github.com/jonashaag/bjoern/blob/master/setup.py#L33-L35).
