### ISSUE TITLE
Compilation terminated - fatal error: http_parser.h: No such file or directory

### ISSUE THREAD

**Issue by yarunachalam** [jonashaag/bjoern#237]
[   17s] gcc -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -DOPENSSL_LOAD_CONF -fwrapv -fno-semantic-interposition -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -fPIC -DSIGNAL_CHECK_INTERVAL=0.1 -DWANT_SIGNAL_HANDLING=yes -DWANT_SIGINT_HANDLING=yes -Ihttp-parser -Istatsd-c-client -I/usr/include/libev -I/opt/local/include -I/usr/include/python3.8 -c bjoern/_bjoernmodule.c -o build/temp.linux-x86_64-cpython-38/bjoern/_bjoernmodule.o -std=c99 -fno-strict-aliasing -fcommon -fPIC -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -g
[   18s] In file included from bjoern/wsgi.h:2,
[   18s]                  from bjoern/_bjoernmodule.c:3:
[   18s] bjoern/request.h:5:10: fatal error: http_parser.h: No such file or directory
[   18s]     5 | #include "http_parser.h"
[   18s]       |          ^~~~~~~~~~~~~~~
[   18s] compilation terminated.
[   18s] error: command '/usr/bin/gcc' failed with exit code 1

**Comment by jonashaag** [comment]
https://github.com/jonashaag/bjoern/wiki/Installation
