### ISSUE TITLE
Extending to asgi

### ISSUE THREAD

**Issue by jefcolbi** [jonashaag/bjoern#238]
Bjoern is a fantastic server, i used it myself and convinced my company to start using instead of gunicorn.

But today webapps need real-time features. The current ASGI servers are not good as they should. It is egoist, but i want to ask to the authors if they can extend bjoern to support the ASGI protocol or start a new projet to create an ASGI server performant like Bjoern.

This project https://github.com/uNetworking/uWebSockets could be a starting point.

Thank you for reading!

**Comment by jonashaag** [comment]
Thanks a lot for the feedback but I don’t have any plans for that.

**Comment by jonashaag** [comment]
Btw how is „real time“ related to „async I/O“?

**Comment by jefcolbi** [comment]
I guess it is required to implement websockets? i have not seen websockets implementation with WSGI. Can you correct me?

**Comment by jonashaag** [comment]
I think so! Eg. this https://github.com/20tab/Bombertab has been available for 10 years.

**Comment by jefcolbi** [comment]
Thank you. I will search how i can mix bjoern + django + websocket (django-channels maybe).

**Comment by jefcolbi** [comment]
You can read this https://channels.readthedocs.io/en/1.x/deploying.html?highlight=django#run-interface-servers and give me your opinion? Maybe we can dive in it and update the documentation for this case.

**Comment by jonashaag** [comment]
Interesting. I’m not sure what ASGI has that WSGI doesn’t that makes it support websockets better. But I haven’t looked into websockets at all so far.
