### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by AnkS4** [jonashaag/bjoern#239]
Installation error with pip

Error Log
https://gist.githubusercontent.com/AnkS4/5b8de3ebd4a400b5259e6733cbcbba8d

Dependencies are installed:
pacman -S libev libevdev gcc

Python Version: 3.8.5
Platform: Manjaro Linux

**Comment by jonashaag** [comment]
There is a package on conda-forge :) otherwise to install a package that requires compilation you need to install the compilers and dependencies in the env, not via the OS level package manager
