### ISSUE TITLE
Python 3 support (PEP 3333)

### ISSUE THREAD

**Issue by jonashaag** [jonashaag/bjoern#29]
if someone else volunteers to do this just ask me about it :)

**Comment by b4stien** [comment]
An old issue revival to let you know that bjoern is still the only WSGI server with a SO_REUSEPORT implementation. Too bad we can't use it.

**Comment by jonashaag** [comment]
Are you sure? This is a standard feature every server should implement

**Comment by b4stien** [comment]
- [Waitress](https://github.com/Pylons/waitress/search?utf8=%E2%9C%93&q=SO_REUSEPORT)
- [CherryPy](https://github.com/cherrypy/cherrypy/search?utf8=%E2%9C%93&q=SO_REUSEPORT)
- [gunicorn](https://github.com/benoitc/gunicorn/search?utf8=%E2%9C%93&q=SO_REUSEPORT)
- [Werkzeug](https://github.com/pallets/werkzeug/search?utf8=%E2%9C%93&q=SO_REUSEPORT)
- [meinheld](https://github.com/mopemope/meinheld/search?utf8=%E2%9C%93&q=SO_REUSEPORT)

With some of these servers you can pass an already opened socket, but in most cases it's so convoluted you'll regret even thinking about it.

To be fair uWSGI probably supports it in some way, but the documentation is killing me.

**Comment by soar** [comment]
I found this project too late :-( All this time I dreaming about lightweight Python web-server, without any dances around nginx. Do you really have no plans about Python3?

**Comment by jonashaag** [comment]
No, but it shouldn't be too complicated to implement, so feel free if you have some experience with CPython C API (or are willing to learn it)!

**Comment by willneumob** [comment]
Wait, Bjoern doesn't support Python 3, in 2017, and this issue is still open? Wow. I guess this is not a viable option for a project :(

**Comment by yanghao** [comment]
@jonashaag I picked up and made it working for python3 ... not sure if this is clean enough to be merged but comments/suggestions are welcome. :-)
