### ISSUE TITLE
Benchmark versus uwsgi

### ISSUE THREAD

**Issue by thedrow** [jonashaag/bjoern#75]
How is bjoern performing comparing to uwsgi?
Both of them are written in C.
What are the differences?

**Comment by paulocheque** [comment]
Here some benchmarks fore reference: http://benchmarks.codeart.io

**Comment by thedrow** [comment]
@paulocheque Very nice. But why did you benchmark with only one worker?

**Comment by paulocheque** [comment]
Yes, only one. 
ps: I will add some contact screen so everyone can send suggestions for improvements

**Comment by thedrow** [comment]
@paulocheque Yeh but why did you benchmark with only one worker?

**Comment by paulocheque** [comment]
yes

**Comment by jonashaag** [comment]
To be honest, these results don't look very reliable. Did you use multiple runs? (At least 10 per configuration)

Plus what @thedrow said, you should probably include benchmarks for 1, 2, 4, … workers.

**Comment by paulocheque** [comment]
Thanks for the feedback. It was in the page that the "trials" in the TODO list. Thanks for the feedback!
Just for one toolset I tested with multiple workers. I also need to automate this! Thanks again!

**Comment by paulocheque** [comment]
I ran again the tests with 50k requests with multiple runs (2 per config). I made some adjustments but I will always try to improve the tests! Thanks for the feedbacks and be free to always send more suggestions! Best,

**Comment by paulocheque** [comment]
some improvements: http://benchmarks.codeart.io/?filter_server=bjoern

**Comment by saitam1** [comment]
Check this:
https://blog.appdynamics.com/engineering/a-performance-analysis-of-python-wsgi-servers-part-2/

**Comment by bulletmark** [comment]
@saitam1 that is an old analysis to be suddenly posting here. Bjoern does not support Python 3 so is largely irrelevant now.

**Comment by jonashaag** [comment]
@bulletmark New release with Python 3 support out now :)

**Comment by bulletmark** [comment]
@jonashaag Thanks for the heads up. I have changed my Python 3 app to use Bjoern. Seems to be working fine. Will let you know how it stands up over time.

**Comment by yechiel-optimalq** [comment]
I read somewhere that we should configure Bjoern to use multi core, any idea on how / some wiki reference / anything ?
What is the recommended setup for Bjoern ?

**Comment by jonashaag** [comment]
You can use receive steering on Linux, see https://github.com/jonashaag/bjoern/blob/3b46a6bba24929a3413eaa1f4da66bedc7ce9dff/bjoern.py#L24 and/or fork, see https://github.com/jonashaag/bjoern/blob/master/tests/fork.py
