### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by paulocheque** [jonashaag/bjoern#83]
Could you include some benchmarks in https://github.com/TechEmpower/FrameworkBenchmarks?

http://www.techempower.com/benchmarks/#section=code&hw=peak&test=query

**Comment by vin18** [comment]
Is there something wrong with the way I have run Bjoern ? Benchmarking Gunicorn vs Bjoern with hello-world POST request.

http://stackoverflow.com/questions/41531707/bjoern-v-s-gunicorn-post-requests?noredirect=1#comment70269241_41531707

**Comment by jonashaag** [comment]
What tool are you using for the benchmarks? Are you running them from the same host that the servers run on? Why are you using multiple workers for bjoern?

Don't expect huge differences in speed. Time spent in the web server will be roughly 5%, the other 95% is spent in your application code. For example if you make a single database query in your application code then the choice of web server simply doesn't matter anymore for performance.

**Comment by vin18** [comment]
@jonashaag  I am using Tsung for benchmarking
 No, the tsung node and server nodes are different, however both have same configuration. Ubuntu 12.04.5 LTS (GNU/Linux 3.2.0-115-virtual x86_64)

Using two workers as there are 2 cores on the node.
The flask app simply returns the JSON it go from the POST request.

**Comment by jonashaag** [comment]
I guess you're simply measuring network performance then, however I don't know what's wrong with your setup that you get such different request rates. I suggest you start benchmarking a simple hello world app.

**Comment by vin18** [comment]
@jonashaag 

the flask app I am using just does this:
```
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route('/suggest/', methods=['POST'])
def hello():
    content = request.get_json()
    return jsonify(**content), 200
```

**Comment by jonashaag** [comment]
That's not hello world and you're not running the tests from the same node. Start with the simplest possible setup.
