### ISSUE TITLE
Document (implement?) logging

### ISSUE THREAD

**Issue by sebastien** [jonashaag/bjoern#87]
Right now Bjoern does not seem to have any logging capability. It would be nice to provide an option (or a callback) to do it. Alternatively, I guess the option is to use a logging middleware.

**Comment by jonashaag** [comment]
I think the middleware approach is the way to go. Is there anything that can't be done using middleware?

**Comment by sebastien** [comment]
I don't think so -- you're right, that would introduce unnecessary bloat.

**Comment by jonashaag** [comment]
:-)
