### ISSUE TITLE
ignore invalid headers

### ISSUE THREAD

**Issue by kianxineki** [jonashaag/bjoern#90]
I am making a development for the browser online game EVE apparently not valid and sends headers with bjoern am unable to obtain them.

I tried it with fapws3 and eventlet in them seems to work well.

I had the same problem with nginx I've solved this way:
http://nginx.org/en/docs/http/ngx_http_core_module.html#ignore_invalid_headers

All tests have been using bottlepy

**Comment by jonashaag** [comment]
Hi, thanks for the feedback. Could you please obtain the raw HTTP request that is being made?

You can use this script as a server:

```py
import socket

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.bind(('localhost', 8000))
sock.listen(1000)

while 1:
    client, _ = sock.accept()
    data = client.recv(1)
    while data[-4:] != '\r\n\r\n':
        data += client.recv(1)
    client.send("HTTP/1.1 404 Not Found\r\nConnection: close\r\n\r\nNot found")
    client.close()
    print("Raw request:\n%r" % data)
```

**Comment by kianxineki** [comment]
Raw request:
`
"GET /15/update/070b10c4-8267-4f97-bfcf-b2a001c29459/J135038 HTTP/1.0\r\nHost: nginx-xn--3-qga.com:9998\r\nConnection: close\r\nUser-Agent: Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US) AppleWebKit/532.0 (KHTML, like Gecko) Chrome/3.0.195.27 Safari/532.0 EVE-IGB\r\nReferer: http://xn--3-qga.com/15/fleet/070b10c4-8267-4f97-bfcf-b2a001c29459\r\nCache-Control: max-age=0\r\nEVE_SHIPNAME: ? O'O ?\t\r\nEVE_SOLARSYSTEMID: 31000021\r\nAccept: application/json, text/javascript, */*; q=0.01\r\nEVE_CORPNAME: Anonimos Multiservis\r\nX-Requested-With: XMLHttpRequest\r\nEVE_CONSTELLATIONID: 21000312\r\nEVE_SHIPID: 1020088691024\r\nEVE_CONSTELLATIONNAME: A-C00312\r\nEVE_CORPROLE: 36028797018963968\r\nEVE_CHARID: 96053105\r\nEVE_SHIPTYPENAME: Astero\r\nEVE_SHIPTYPEID: 33468\r\nEVE_CORPID: 98456577\r\nEVE_SOLARSYSTEMNAME: J135038\r\nEVE_REGIONNAME: A-R00001\r\nEVE_REGIONID: 11000001\r\nEVE_TRUSTED: Yes\r\nEVE_SERVERIP: 87.237.34.200:26000\r\nEVE_CHARNAME: Toloveo O'O\r\nAccept-Encoding: gzip,deflate\r\nAccept-Language: en-us,en\r\nAccept-Charset: iso-8859-1,*,utf-8\r\n\r\n"
`

**Comment by jonashaag** [comment]
This isn't even an invalid HTTP request. The problem is that the (very old) version of http-parser we're using does not support underscores in HTTP header field names. We can either inline the old version of http-parser into this repo and fix it there, or we can update to the latest version of http-parser (#50).

**Comment by kianxineki** [comment]
which would be the easiest? currently version of http-parser that we work very well, the new version is better? Currently I have service with eventlet, but the yield is very low compared to bjoern: P

Any option is worth me, it might be simpler to make a fix for the current version?

Thank you !

**Comment by jonashaag** [comment]
> Any option is worth me, it might be simpler to make a fix for the current version?

Definitely!
