### ISSUE TITLE
Considering libuv ?

### ISSUE THREAD

**Issue by sideffect0** [jonashaag/bjoern#93]
Considering https://github.com/libuv/libuv ?

**Comment by jonashaag** [comment]
What would you use it for?

**Comment by sideffect0** [comment]
@jonashaag `wsgi` :smile: :+1:

**Comment by jonashaag** [comment]
What does libuv have to do with WSGI? What advantages does libuv have over libev for bjoern?

**Comment by sideffect0** [comment]
@jonashaag please check the features 3:)
