### ISSUE TITLE
Realloc failing with "Invalid Next Size"

### ISSUE THREAD

**Issue by ambasta** [jonashaag/bjoern#95]
Hi,

I'm running bjoern with chaussette and circus. However, I've noticed that journalctl contains a lot of messages as:

 *** Error in `/usr/bin/python /usr/bin/chaussette --fd 5 --backend bjoern bjoern-wsgi.application': realloc(): invalid next size: 0x000000000388e800 ***

The configuration of circus launching bjoern is as:
```
[circus]
check_delay = 5
statsd = False
httpd = False

[watcher:express-watcher]
cmd = chaussette
args = --fd $(circus.sockets.express) --backend bjoern bjoern-wsgi.application
use_sockets = True
numprocesses = 9
working_dir = /home/admin/express
virtualenv = /home/admin/.virtualenvs/express
virtualenv_py_ver = 2.7
copy_env = True

[env:express-watcher]
PYTHONPATH=/home/admin/express
DJANGO_SETTINGS_MODULE=settings
SETTINGS=production
NEW_RELIC_CONFIG_FILE=/home/admin/express/environments/newrelic.ini

[socket:express]
path = /tmp/bjoern.sock
family = AF_UNIX
```

while the uwsgi application in question is (Django):
```
import newrelic.agent
from django.core.wsgi import get_wsgi_application

newrelic.agent.initialize()

def application(environ, start_response):
    return newrelic.agent.WSGIApplicationWrapper(
            get_wsgi_application())(environ, start_response)
```

**Comment by jonashaag** [comment]
Are you sure the realloc failure is a problem in bjoern?

**Comment by delhivery-automagic** [comment]
How do I isolate the issue to verify?

**Comment by ambasta** [comment]
How do I isolate the issue to verify? Given that the circus and chaussette are python applications, my first assumption was bjoern causing realloc, though I am not so sure any more.

**Comment by jonashaag** [comment]
There are multiple implementations of malloc for debugging, but I haven't used any of them yet. You can also use gdb and set a breakpoint a `realloc`
